### ISSUE TITLE
How to delete plugin

### ISSUE THREAD

**Issue by GoshaEgorian** [welovecoding/editorconfig-netbeans#106]
If you have NetBeans 8.2, plugin doesn't work. But you need to use IDE. How to delete plugin?

[Related issue](https://github.com/welovecoding/editorconfig-netbeans/issues/103).

**Comment by wadechandler** [comment]
Tools|Plugins|Installed and click to "Show Details", find it, check it,
choose uninstall.

Wade

**Comment by GoshaEgorian** [comment]
@wadechandler thanks! I missed "Show Details" button, now it's OK, plugin was deactivated.

**Comment by bennyn** [comment]
Happy to hear that the problem is solved. Thanks for your help @wadechandler. 😃
