### ISSUE TITLE
Invalid Java Version for EditorConfig on Netbeans 9.0

### ISSUE THREAD

**Issue by kg6zvp** [welovecoding/editorconfig-netbeans#115]
I just installed EditorConfig on my brand new NetBeans 9.0 install using OpenJDK 11 on Fedora 28.

I received the following message: "The EditorConfig plugin needs at least Java 8 to work. Please consider to update to Java 8."

**Comment by ZaLiTHkA** [comment]
interesting... I noticed the same sort of message from a Gradle Wrapper build script recently when I tried to run it with JDK 10.

perhaps something with how the JDK version is checked (i.e.: JDK `8` is `1.8` internally)?

**Comment by kg6zvp** [comment]
@ZaLiTHkA Could be. :man_shrugging: Embarrassingly enough I haven't looked at the source code for this extension, I've just been using it.

**Comment by emabrey** [comment]
This comes down to us using a regex to check version information instead of using the Netbeans platform class to verify the JDK version. I have a fix I will be pull requesting for comments.

**Comment by emabrey** [comment]
@kg6zvp @ZaLiTHkA 

[Here](https://www.dropbox.com/s/zf885m2uo047k9h/editorconfig-0.10.4-SNAPSHOT.nbm?dl=0) is a copy of the plugin module build of a proposed fix. Please download and [manually install the plugin](http://wiki.netbeans.org/FaqPluginInstall) to test if the bug is fixed on your machines.

**Comment by ZaLiTHkA** [comment]
Thanks @emabrey, I'll check it out when I get back to work just now. :)

**Comment by tekapo** [comment]
Thanks @emabrey ! 
Your fix, editorconfig-0.10.4-SNAPSHOT.nbm, works fine with NetBeans 11.1 on:
```
Java: 13; OpenJDK 64-Bit Server VM 13+33
Runtime: OpenJDK Runtime Environment 13+33
```

**Comment by bennyn** [comment]
@emabrey Is [this](https://github.com/emabrey/editorconfig-netbeans/commit/2af1f45632eac81157c86fa28f316b221e1ddd4c) the fix? If yes, we can apply it and create an official v0.10.4 [release](https://github.com/welovecoding/editorconfig-netbeans/releases). :)

**Comment by bennyn** [comment]
Thanks for your feedback @tekapo. We just created an official [v0.10.4](https://github.com/welovecoding/editorconfig-netbeans/releases/tag/v0.10.4). 🎉
