### ISSUE TITLE
end_of_line doesn't work

### ISSUE THREAD

**Issue by LeMyst** [welovecoding/editorconfig-netbeans#120]
How to reproduce:

- Netbeans 8.2 (PHP) or 9 - Windows 10
- editorconfig-netbeans v0.10.4
- Source file have "CR" ending line
- .editorconfig

```
root = true

[*]
end_of_line = crlf
insert_final_newline = true
charset = utf-8
```

Current result:
Ending line is not modified to the requested value

Expected result:
"CR" ending line become "CRLF" (or "LF")

Log:
```
INFO [com.welovecoding.nbeditorconfig.processor.EditorConfigProcessor]: "end_of_line": CRLF (C:/Users/Myst/Documents/NetBeansProjects/bifrost/application/views/admin/common_header.php)
INFO [com.welovecoding.nbeditorconfig.processor.operation.LineEndingOperation]: ¬ Changed line endings
```

**Comment by ve3** [comment]
I'm using Netbeans 8.2 on Windows 10.
It is not just `end_of_line` doesn't work but many properties doesn't work.

```
# top-most EditorConfig file
root = true

# Matches multiple files with brace expansion notation
[*.{css,htm,html,js,json,md,php}]
charset = utf-8
end_of_line=crlf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 4
```

From my config: `end_of_line`, `insert_final_newline`, `trim_trailing_whitespace` are not working.
Other than this, I'm not sure because my Netbeans settings is already did that.
