### ISSUE TITLE
Syntax Highlighting for .editorconfig files

### ISSUE THREAD

**Issue by bennyn** [welovecoding/editorconfig-netbeans#39]
It would be great if you get syntax highlighting if you open an `.editorconfig` file in the NetBeans editor. At the moment all the texts are just black. We can maybe make use of NetBeans highlighting when changing the mime type from `"text/plain+ec"` to something supported (like CFG files).

**Comment by bennyn** [comment]
Nice read: [NetBeans Manifest File Syntax Highlighting Module Tutorial](https://platform.netbeans.org/tutorials/nbm-mfsyntax.html)

**Comment by Yserz** [comment]
I think we can close this issue, am I right? ;P
