### ISSUE TITLE
nbm files

### ISSUE THREAD

**Issue by junichi11** [welovecoding/editorconfig-netbeans#46]
nbm file exists in the dist directory of this repository now.
IMHO, nbm files should be attached to releases[1] for each versions.

[1] https://github.com/welovecoding/editorconfig-netbeans/releases

Thanks.

**Comment by bennyn** [comment]
Very good idea. Will be done immediately.

You can find the `.npm` files now attached to the releses. There is also `v0.0.3-beta` now which includes the MIME type change to `text/x-editorconfig`. :smiley: 

Check here:
https://github.com/welovecoding/editorconfig-netbeans/releases/tag/v0.0.3-beta

**Comment by junichi11** [comment]
:+1:
