### ISSUE TITLE
Editor shows error when all properties are commented

### ISSUE THREAD

**Issue by bennyn** [welovecoding/editorconfig-netbeans#48]
I created an `.editorconfig` file with the following properties:

```ini
root = true

[*]
# charset = utf-8
# indent_style = space
# indent_size = 2
# end_of_line = lf
# insert_final_newline = true
# trim_trailing_whitespace = true
```

As you can see all properties are commented so nothing should happen. But the EditorConfig editor shows this error in the IDE editor:

> mismatched input '<EOF>' expecting {'root', 'charset', 'end_of_line', 'indent_size', 'indent_style', 'insert_final_newline', 'max_line_length', 'tab_width', 'trim_trailing_whitespace', PROPERTY_KEY_UNKNOWN}

**Comment by junichi11** [comment]
I'll fix it. (I thought that user may forget to add properties.)
Thanks.

**Comment by bennyn** [comment]
Cool! :smiley:  You can show a warning if you want and if possible but showing an error is a bit to harsh.
