### ISSUE TITLE
Choosing a license for our code

### ISSUE THREAD

**Issue by bennyn** [welovecoding/editorconfig-netbeans#50]
Before releasing our plugin to the [NetBeans Plugin Portal](http://plugins.netbeans.org/), we need to define a license for our code.

I think that our main goals with a license should be:

- Make to code freely available to other developers
- Make sure that the NetBeans IDE team can integrate our code in their code base / product
- Make sure that we can get some credits (if possible)

I will read some more articles before coming up with license suggestions. 
Here are some nice posts about open-source software licenses:
- [ZDNet — Greg Stein: Three is enough](http://www.zdnet.com/article/greg-stein-three-is-enough/)
- [Google Open Source Blog — Standing Against License Proliferation](http://google-opensource.blogspot.de/2008/05/standing-against-license-proliferation.html)
- [O'Reilly Media — The MIT, BSD, Apache, and Academic Free Licenses](http://www.oreilly.com/openbook/osfreesoft/book/ch02.pdf)

**Comment by galeksandrp** [comment]
Well, http://choosealicense.com, MIT.

**Comment by bennyn** [comment]
@sindresorhus has also chosen MIT license for his [atom-editorconfig(https://github.com/sindresorhus/atom-editorconfig/blob/master/license).

**Comment by bennyn** [comment]
Added the MIT license because it is less strict than GPL v2: http://stackoverflow.com/a/11752204/451634
