### ISSUE TITLE
SEVERE: java.lang.UnsupportedClassVersionError: com/welovecoding/nbeditorconfig/editor/csl/EditorConfigLanguage : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by craiglondon** [welovecoding/editorconfig-netbeans#54]
Not sure how else to contribute to this issue, this was in my log.  Not sure if this plugin is working with this error or not.

Did an install from NBM, restart, git add, git commit, checked log.

Environment
WIndows 8.1
Netbeans 8.0.2

```
SEVERE: java.lang.UnsupportedClassVersionError: com/welovecoding/nbeditorconfig/editor/csl/EditorConfigLanguage : Unsupported major.minor version 52.0
```

**Comment by Yserz** [comment]
Hey,

which version of Java is your NetBeans using?

**Comment by craiglondon** [comment]
```
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.7.0_76; Java HotSpot(TM) 64-Bit Server VM 24.76-b04
Runtime: Java(TM) SE Runtime Environment 1.7.0_76-b13
System: Windows 8 version 6.2 running on amd64; Cp1252; en_US (nb)
User directory: C:\Users\Craig\AppData\Roaming\NetBeans\8.0.2
Cache directory: C:\Users\Craig\AppData\Local\NetBeans\Cache\8.0.2
```

**Comment by Yserz** [comment]
Thanks for your response.
The problem is that your NetBeans is running with Java 7. Currently only Java 8 is supported by the plugin.

**Comment by craiglondon** [comment]
That would do it.  Did I miss the Java 8 requirement in the documentation?

**Comment by craiglondon** [comment]
Uhh.. yeah sorry.  Thanks for your patience.

```Requires Java 8```

**Comment by Yserz** [comment]
No problem. Feel free to open further issues if you find any errors. We are always happy to receive messages from users :)

**Comment by craiglondon** [comment]
Should I open a new ticket for this question?   I updated to Java 8, checked that Netbeans is using 8.  How do I tell if the plugin is running?

**Comment by Yserz** [comment]
1. A .editorconfig file is needed. You can add the file with the normal NetBeans "add file" function. Put the file in a folder you want to influence.
2. Add rules to the editorconfig. E.g.: 
```
[*.java]
indent_style = space
indent_size = 4
```
to set the indent size to 4 spaces for all java files in that particular folder.
As soon as you save the editorconfig OR a file influenced by an editorconfig the plugin will be triggered and set the indent size to 4 spaces.

See http://editorconfig.org/ for more information.

**Comment by craiglondon** [comment]
Thanks for your help.

Here is the .editorconfig file I have created, I primilary deal with CSS, JS, and PHP.  I use NetBeans and SublimeText2.  Sometimes I work on Windows servers, but mostly on Linux servers, so I wanted to get the line endings to be client/project specific.

```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# Matches multiple files with brace expansion notation
# Set default charset
[*.{js,php}]
charset = utf-8

# Tab indentation (no size specified)
# [*.js]
[*.{js,php}]
indent_style = space
indent_size = 2
insert_final_newline = false
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

# Matches the exact files either package.json or .travis.yml
[{package.json,.travis.yml}]
indent_style = space
indent_size = 2


```

**Comment by Yserz** [comment]
I tried your example (with some little modifications) and found an error with the trailing whitespace feature. I already submitted a pull request for that here: https://github.com/welovecoding/editorconfig-netbeans/pull/56 . Was that the error you encountered?
