### ISSUE TITLE
How to keep updated....

### ISSUE THREAD

**Issue by craiglondon** [welovecoding/editorconfig-netbeans#70]
How would you suggest I keep my plugin updated with the latest version?  Is there an RSS I can subscribe to or email list?

**Comment by Yserz** [comment]
In general you can check the releases page here on GitHub.
![ghrelease](https://cloud.githubusercontent.com/assets/1138344/7075126/e8ef83a2-deff-11e4-94f3-6b242a75078d.png)

For tracking releases on GitHub i'll refer to this page: [Releasetracking](http://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases)

Once we published the plugin on the plugin center you'll get notified through netbeans.

**Comment by bennyn** [comment]
Reminds me of publishing **v0.0.6-beta**. ;)

**Comment by craiglondon** [comment]
Thanks for the tips.  I'll check them out.   I just updated from 0.0.4 to 0.0.5, and I'll update to 0.0.6 very soon!
