### ISSUE TITLE
It doesn't work in Netbean 8.0.2

### ISSUE THREAD

**Issue by talamaska** [welovecoding/editorconfig-netbeans#72]
org.netbeans.InvalidException: StandardModule:com.welovecoding.netbeans.plugin.editorconfig jarFile: C:\Users\****\AppData\Roaming\NetBeans\8.0\modules\com-welovecoding-netbeans-plugin-editorconfig.jar: java.lang.UnsupportedClassVersionError: com/welovecoding/nbeditorconfig/listener/Installer : Unsupported major.minor version 52.0

java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by ZaLiTHkA** [comment]
Is your Netbeans using Java 7 by any chance..? As stated in the readme, this plugin requires 8 in order to run.

**Comment by talamaska** [comment]
hm, you were right, I checked in the netbeans.conf and I saw jre7 was set. Thanks for the direction.

**Comment by bennyn** [comment]
Hey guys, thanks for your reports. It makes me very happy to see that our plugin is of interest.

@talamaska: Does it work now for you with Java 8?
@ZaLiTHkA: Thank you for your support! Really great!

**Comment by talamaska** [comment]
Well
it didn't recognize the normal .editorconfig already created file, it doesn't show it in the file structure.
when I create it manually from the UI it creates a .editorconfig.editorconfig file and my Netbeans turns black and I think crashed. Restarted netbeans, very slow scan. I still don't see any of the editorconfig files and I'm not sure how to verify if it is working.

**Comment by ZaLiTHkA** [comment]
@bennyn, only a pleasure. I tend to chime in and help when I'm around and where I can. :)

@talamaska, shortly after my comment above, I created #73 with a similar file naming situation as what you're describing. I don't remember having any problem with NB not reading config files though.. I'll post back here if I find anything useful.

**Comment by talamaska** [comment]
ok, netbeans is hiding a lot of (dot) files by default, I have figured that out there is a regex pattern in its settings.

**Comment by bennyn** [comment]
Yepp. NetBeans hides the `.editorconfig` files by default but you can change it's regex pattern to:

```
^(CVS|SCCS|vssver.?\.scc|#.*#|%.*%|_svn)$|~$|^\.(?!htaccess|editorconfig|jshintrc|DS_Store|gitattributes|gitignore$|.*\.yml$).*$
```

**Screenshot**

![](http://picload.org/image/iorlrci/screenshot-1.png)

**Comment by odan** [comment]
I get the same error message like talamaska.

My Netbeans setup:
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.7.0; Java HotSpot(TM) 64-Bit Server VM 21.0-b17
Runtime: Java(TM) SE Runtime Environment 1.7.0-b147
System: Windows 7 version 6.1 running on amd64; Cp1252; de_DE (nb)
User directory: C:\Users\User\AppData\Roaming\NetBeans\8.0.2
Cache directory: C:\Users\User\AppData\Local\NetBeans\Cache\8.0.2

**Comment by bennyn** [comment]
Hi @odan,

Thank you for your bug report! Telling from your log I can see that you are running Java 7 but the EditorConfig plugin needs Java 8. So if you use Java 8, everything should be fine.

Please report back if upgrading to Java 8 solves your problem.

Best,

Benny

**Comment by odan** [comment]
Hi @bennyn, Java 8 has solved the problem. Thanks!

**Comment by bennyn** [comment]
Solutions to this problem have been added to our [FAQ page](https://github.com/welovecoding/editorconfig-netbeans/wiki/FAQ). Thanks for reporting!
