### ISSUE TITLE
Editorconfig is completelly skipped for php projects

### ISSUE THREAD

**Issue by johnny-bit** [welovecoding/editorconfig-netbeans#74]
Hi,

I'm using 0.0.6-beta and I've noticed that in logs listeners are correctly applied for web projects (HTML5 icon), but are completely ignored for php projects. I've also noticed that .editorconfig files are not listed for HTML5 projects not are for PHP projects.

**Comment by bennyn** [comment]
Hi Johnny,

thanks for reporting this issue. In your NetBeans PHP project there must be a folder called `nbproject` which has a `project.xml` file. 

Can you please post the contents of your `project.xml` file? The `<type>` property is interesting for us. It must be something like: `<type>org.netbeans.modules.web.clientproject</type>`. I think for your project it shows `org.netbeans.modules.php.project`, am I right?

**Comment by johnny-bit** [comment]
Hi Benny!

Exactly! Have a look:

```
$ cat project.xml 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.netbeans.org/ns/project/1">
    <type>org.netbeans.modules.php.project</type>
    <configuration>
        <data xmlns="http://www.netbeans.org/ns/php-project/1">
            <name>sagextras</name>
        </data>
    </configuration>
</project>
```

**Comment by johnny-bit** [comment]
I wonder is it possible to say instead of "suport following set of project types" to "support all project types" when dealing with netbeans? Otherwise You'd need to figure out all project types and explicitly reference them.

**Comment by bennyn** [comment]
Applying the plugin for all project types would be nice but the [NetBeans Project Type Extension Module Tutorial](https://platform.netbeans.org/tutorials/nbm-projectextension.html#intro) says that you need to specify the types.

I just built you [v0.0.7-beta](https://github.com/welovecoding/editorconfig-netbeans/releases/tag/v0.0.7-beta), which should work for PHP projects. 
Can you tell me if this works for you?

**Comment by FinBoWa** [comment]
Just tested this and it works but should it actually format files automatically without the users explicitly saving the file first?

Eg. I opened a legacy project and during the project load it formatted all files.

**Comment by johnny-bit** [comment]
Hi! Yes, looks like 0.0.7 works very nice :)

**Comment by ZaLiTHkA** [comment]
@FinBoWa, perhaps just my opinion, but I think that behaviour might be somewhat dangerous.. How would you ensure it didn't try reformat any minified libraries in your project folder?

Using the *current styling rules* when creating and/or saving a file seems like the all-round safest idea.

**Comment by FinBoWa** [comment]
Im not keen on this automatically formatting a project without me actually saving a file.

I opened a Magento project and it went and formatted all files automatically. Of course I could specify that skip them but personally Id expect it only to format if i ask it to or save the file. Not automatically on files that I haven't touched.

**Comment by ZaLiTHkA** [comment]
My apologies; I completely misread your message.. (:

**Comment by bennyn** [comment]
Might be a good idea to fomat only when the user clicks on save. We could also add an option for users who really want to format their whole project. What do you think @Yserz &  @junichi11?

**Comment by FinBoWa** [comment]
@bennyn running this when user calls format on a specific project folder would handle that "whole project" also. Should also fire when user calls format on the opened file of course.

**Comment by FinBoWa** [comment]
and not missing of course formatting on save :)

**Comment by FinBoWa** [comment]
Personally I think formatting could (or should) be an action from a user, not something automatic per ce. 

But I assume that on Sublimitext it runs on save always or is that correct so if its somewhat expected to this run on save then it would be in line how others have implemented it.

**Comment by bennyn** [comment]
Because of your requests we will change the formatting behaviour of our EditorConfig plugin. In the future it will only touch files if you save them. As this issue here is about making it work for PHP projects (which is solved now!) I will close this issue. Thank you so much for your valuable feedback!
