### ISSUE TITLE
Editorconfig scans & changes everything on open project

### ISSUE THREAD

**Issue by johnny-bit** [welovecoding/editorconfig-netbeans#77]
Hello,

I have hard time dealing with editorconfig and projects with huge dependencies. For example I have following editorconfig (instead of * I use include):
```
[{/*,/assets/*]
indent_tyle = space
indent_size = 2
```
yet every project opening is cpu & I/O intensive with log filling with messages from plugin for dirs like bower_components, dist, node_modules (all of those are in gitignore too!)

Is there a way for plugin to ignore some dirs for editorconfig without hiding them form netbeans?

**Comment by jyrkij** [comment]
I'd rather have editorconfig apply changes only on save. Or even only on format. There's more conversation in #74.

**Comment by t3dev** [comment]
+1 @jyrkij applying changes without even opening the file is a nogo. please just reformat on an explicit call to format or at least give a chance to disable auto reformatting.

**Comment by bennyn** [comment]
I created an issue for that: https://github.com/welovecoding/editorconfig-netbeans/issues/80

Please follow that issue (comment it with `+1`), when you want to watch the status of this feature.
