### ISSUE TITLE
java.lang.UnsupportedClassVersionError: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by shellcatt** [welovecoding/editorconfig-netbeans#79]
I'm JDK 1.7 as home VM & can't activate your plugin in NetBeans 8.0.2 on Kubuntu 12.04 after installing it :( 

org.netbeans.InvalidException: StandardModule:com.welovecoding.netbeans.plugin.editorconfig jarFile: ~/.netbeans/8.0/modules/com-welovecoding-netbeans-plugin-editorconfig.jar: java.lang.UnsupportedClassVersionError: com/welovecoding/nbeditorconfig/listener/Installer : Unsupported major.minor version 52.0

**Comment by bennyn** [comment]
Hi @shellcatt, you need to run Java 8 in order to use our plugin. 

With the command `java -version` you can find out on your command prompt / terminal which version you are using. You need `java version "1.8.0"` or later.

**Comment by shellcatt** [comment]
Oh, thx a lot @bennyn :) It seems to work fine now.
Is there a reason why I can't see the .editorconfig file in the Projects window?

**Comment by bennyn** [comment]
NetBeans hides the .editorconfig files by default but you can change it's regex pattern to:

```
^(CVS|SCCS|vssver.?\.scc|#.*#|%.*%|_svn)$|~$|^\.(?!htaccess|editorconfig|jshintrc|DS_Store|gitattributes|gitignore$|.*\.yml$).*$
```

See: https://github.com/welovecoding/editorconfig-netbeans/issues/72

**Screenshot**

![](http://picload.org/image/iorlrci/screenshot-1.png)

**Comment by ZaLiTHkA** [comment]
@shellcatt, to cover a different side of the same coin: The "Projects" view in NetBeans only shows the contents of special project folders, so you won't see your `.editorconfig` file there if it's in the root of your project (next to your `build.xml` for example)

Try moving the config file to your project's defined "Source Packages Folders" for Java files, and/or your "Web Pages Folder" for web app files. Alternatively you can access all files in your project root folder through the "Files" panel.

**Comment by bennyn** [comment]
Thanks for clarification, @ZaLiTHkA. 

As this question has been asked already I will add it's answer to our [FAQ page](https://github.com/welovecoding/editorconfig-netbeans/wiki/FAQ).

@shellcatt - Please open a new ticket if you have other questions as this issue here seems to be resolved now.

**Comment by shellcatt** [comment]
Yep, thanks a lot guys :)

**Comment by halfer** [comment]
Just encountered this error, thanks for the information that a later Java version is required. Would it be possible to test the Java version in the initialisation code, and output an appropriate error? Something like:

> The EditorConfig plugin needs Java 8 (1.8.0) or later to run.
