### ISSUE TITLE
Support Java 7

### ISSUE THREAD

**Issue by bennyn** [welovecoding/editorconfig-netbeans#81]
As per https://github.com/welovecoding/editorconfig-netbeans/issues/62 we should make the plugin work with Java 7.

**Comment by phptek** [comment]
This would be awesome. I run Nb 8.0.2 on Ubuntu 14.04 which comes with Java 7. Have you seen the hoops to jump through to get Java 8 on there? http://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts

**Comment by bennyn** [comment]
Hi @phptek, we have received a very nice pull request from @markiewb which brings in support for Java 7. So there is a [release version 0.1.0](https://github.com/welovecoding/editorconfig-netbeans/releases/tag/v0.1.0) now. Can you please download the **editorconfig-0.1.0.nbm** file from there and test if it works on your system?

@Yserz When I remember correctly then we had a balloon tip which gave a warning that Java 8 is required. I guess that can be removed now?
